Массовый респрайт СБ
dead-space-server/space-station-14-resources pull request #11
Opened 2024-10-14 17:03 UTC by ilyasassiks

## Описание PR

Массовый респрайт СБ по просьбе хихича
## Изменения для патчноута

* Массовый респрайт СБ
* Добавлена мантия инструктора СБ за 20 часов игры на нем

## Критические изменения

Нет

(все затестил)

2024-10-14 18:17 UTC, qrtDaniil requested changes
Urani отправляется на долгую доработку респрайта

2024-10-14 18:17 UTC, qrtDaniil commented on Resources/Textures/Clothing/Ears/Headsets/security.rsi/meta.json
> +  "copyright": "Made by Urani (discord) for Space Station 14 server Dead Space",
Я вот смотрю на старый спрайт и новый и не понимаю куда из меты пропало `Made by Hqlle and SonicHDC (github)`

2024-10-14 18:17 UTC, qrtDaniil commented on Resources/Textures/Clothing/Eyes/Hud/secpatch.rsi/meta.json
> +  "copyright": "Made by Urani (discord) for Space Station 14 server Dead Space",
То же самое, это респрайт

2024-10-14 18:17 UTC, qrtDaniil commented on Resources/Textures/Objects/Weapons/Guns/Rifles/lecter.rsi/wielded-inhand-left.png
А тут мета вообще не дописана

2024-10-14 18:17 UTC, qrtDaniil commented on Resources/Textures/Objects/Weapons/Guns/Rifles/lecter.rsi/base.png
Не дописана мета

2024-10-14 18:17 UTC, qrtDaniil commented on Resources/Textures/Clothing/Shoes/Boots/winterbootssec.rsi/meta.json
> +  "copyright": "Made by Urani (discord) for Space Station 14 server Dead Space",
Это явный респрайт

2024-12-24 15:59 UTC, krevetkqqq commented
до лучших времен

2024-12-24 15:59 UTC, closed without merging