Alert-Levels-Rules
dead-space-server/space-station-14-resources pull request #14
Opened 2024-10-15 17:45 UTC by killervegetable

## Описание PR

Изменение правил КК для экипажа на актуальные

2024-10-15 17:47 UTC, qrtDaniil requested changes
Описание PR не по форме

2024-10-15 19:15 UTC, killervegetable commented
> Описание PR не по форме > изменил на соответствующее форме
@qrtDaniil

2024-10-16 10:21 UTC, qrtDaniil approved these changes

2024-10-21 16:31 UTC, qrtDaniil commented
У тебя в этом PR-е правила ещё

2024-10-24 16:58 UTC, merged