баклер
dead-space-server/space-station-14-resources pull request #31
Opened 2024-10-24 18:03 UTC by sosooo121

## Описание PR
Щиты на спину

## Изменения для патчноута
* Большую часть щитов теперь можно вешать на спину

## Критические изменения
нет

2024-10-24 18:45 UTC, sosooo121 commented
всё

2024-10-24 19:01 UTC, qrtDaniil requested changes

2024-10-24 19:01 UTC, qrtDaniil commented on Resources/Textures/Objects/Weapons/Melee/riot_laser-shield.rsi/meta.json
> +  "copyright": "Made by PixelTheKermit (github) for SS14",
Пофикси мету, у всех спрайтов из папки shields.rsi в копирайт строчке меты должно быть: `Taken from https://github.com/Citadel-Station-13/Citadel-Station-13/commit/84223c65f5caf667a84f3c0f49bc2a41cdc6c4e3` https://github.com/dead-space-server/space-station-14-resources/blob/master/Resources/Textures/Objects/Weapons/Melee/shields.rsi/meta.json#L4C17-L4C132

2024-10-24 19:01 UTC, qrtDaniil commented on Resources/Textures/Objects/Weapons/Melee/riot_laser-shield.rsi/meta.json
> +  "copyright": "Made by PixelTheKermit (github) for SS14",
И добавь в каждую мету приписку о авторе спрайта на спине

2024-10-25 00:22 UTC, qrtDaniil commented
От-лич-но

2024-10-25 00:22 UTC, qrtDaniil approved these changes

2024-10-25 00:23 UTC, merged