ADD: UEG hardsuits
dead-space-server/space-station-14-resources pull request #48
Opened 2024-11-08 09:49 UTC by KeplyDog

## Описание PR

Добавлены прототипы и спрайты скафандров солдата и командира ОПЗ.

## Изменения для патчноута
* Добавлены скафандры для солдата и командира ОПЗ.

## Критические изменения
Нет.

## P.S.
ПР сделан по просьбе (Discord) @drippenwagen.

2024-11-08 14:25 UTC, qrtDaniil requested changes

2024-11-08 14:25 UTC, qrtDaniil commented on Resources/Textures/DeadSpace/Clothing/Head/Hardsuits/UEGhardsuithelmet.rsi/meta.json
> +  "copyright": "from Space Station 13",
Ссылку на билд, а лучше прямой коммит

2024-11-08 14:25 UTC, qrtDaniil commented on Resources/Textures/DeadSpace/Clothing/Head/Hardsuits/UEGcommhardsuithelmet.rsi/meta.json
> +  "copyright": "from Space Station 13",
Ссылку на билд, а лучше прямой коммит

2024-11-08 14:25 UTC, qrtDaniil commented on Resources/Textures/DeadSpace/Clothing/OuterClothing/Hardsuits/UEGcommhardsuit.rsi/meta.json
> +  "copyright": "from space station 13",
Ссылку на билд, а лучше прямой коммит

2024-11-08 14:25 UTC, qrtDaniil commented on Resources/Textures/DeadSpace/Clothing/OuterClothing/Hardsuits/UEGhardsuit.rsi/meta.json
> +  "copyright": "from space station 13",
Ссылку на билд, а лучше прямой коммит

2024-11-08 14:25 UTC, qrtDaniil commented on Resources/Prototypes/DeadSpace/Entities/Clothing/Head/UEG-helmets.yml
> +  name: шлем скафандра командира ОПЗ
А `description`?

2024-11-08 14:25 UTC, qrtDaniil commented on Resources/Prototypes/DeadSpace/Entities/Clothing/Head/UEG-helmets.yml
> +  name: шлем скафандра солдата ОПЗ
Тоже `description`

2024-11-25 10:39 UTC, KeplyDog commented
Автор прототипа заявил, что спрайты неактуальны, поэтому пр закрывается.

2024-11-25 10:39 UTC, closed without merging