Карта
dead-space-server/space-station-14-resources pull request #5
Opened 2024-10-10 20:16 UTC by sosooo121

## Описание PR
Хирург

## Изменения для патчноута
* Новая роль в медицинском отделе - хирург.

## Критические изменения
нет

2024-10-12 16:02 UTC, qrtDaniil requested changes

2024-10-13 14:43 UTC, qrtDaniil requested changes
А ещё на прототипы карт не добавлена роль

2024-10-13 14:43 UTC, qrtDaniil commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/identification_cards.ftl
>  ent-ResearchAssistantIDCard = ID карта лаборанта
Если добавляешь в файл добавляй по смыслу рядом кинул название должности в файле Resources/Locale/ru-RU/job/job-names.ftl над химиком, кидай везде вещи теперь хирурга над химиком

2024-10-13 14:43 UTC, qrtDaniil commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/pda.ftl
> +    .desc = Красные пятна остались после одной из операций
То же самое что и в предыдущем комментарии

2024-10-13 14:43 UTC, qrtDaniil commented on Resources/Textures/Objects/Misc/id_cards.rsi/idsurgeon.png
Как то всё ещё так себе иконка выглядит

2024-10-13 14:43 UTC, qrtDaniil commented on Resources/Prototypes/Roles/Jobs/Medical/surgeon.yml
> +    neck: ClothingNeckApronCoroner
Не так не пойдёт, снаряжение как доктору ему нужно добавить через лодауты

2024-10-13 18:27 UTC, sosooo121 commented on Resources/Textures/Objects/Misc/id_cards.rsi/idsurgeon.png
просто белая будет так себе, не будет понятно что это скальпель. Может есть идеи что ему туда можно?

2024-10-16 00:07 UTC, qrtDaniil requested changes
Ты жёстко закибербулил Корваксные карты и в их прототипы не добавил хирурга `Resources/Prototypes/Maps/Corvax`

2024-10-18 23:16 UTC, qrtDaniil approved these changes

2024-10-19 16:37 UTC, qrtDaniil requested changes

2024-10-19 16:37 UTC, qrtDaniil commented on Resources/Prototypes/Roles/Jobs/Medical/surgeon.yml
> +  playTimeTracker: JobMedicalSurgeon
playTimeTracker-а такого нет

2024-10-21 16:35 UTC, qrtDaniil approved these changes

2024-10-21 16:35 UTC, merged