Портативный монитор камер ГСБ
dead-space-server/space-station-14-resources pull request #58
Opened 2024-11-24 19:57 UTC by YarikVodila22817

## Описание PR
* Добавлено новый HighRiskItem: портативный монитор камер ГСБ.
* Добавлено новое задание синдиката: украсть портативный монитор камер ГСБ.

## Изменения для патчноута

* Добавлен портативный монитор камер ГСБ.
* Добавлено новое задание синдиката.

## Критические изменения

* Нет

2024-11-24 20:10 UTC, krevetkqqq requested changes

2024-11-24 20:10 UTC, krevetkqqq commented on Resources/Textures/DeadSpace/Objects/Devices/portable_camera_monitor.rsi/meta.json
> +  "copyright": "created by pofitlo",
"Made by regeton (discord) for Space Station 14 server Dead Space"

2024-11-24 20:10 UTC, krevetkqqq commented on Resources/Textures/DeadSpace/Objects/Devices/portable_camera_monitor.rsi/meta.json
> +      "name": "portable_camera_monitor"
сделай название как icon,  а также inhand-right и inhand-left

2024-11-24 20:10 UTC, krevetkqqq commented on Resources/Prototypes/DeadSpace/Entities/Objects/Devices/Securities_Gadgets/portable_camera_monitor.yml
> +  name: portable camera monitor
локализация будет?

2024-11-24 20:10 UTC, krevetkqqq commented on Resources/Prototypes/DeadSpace/Objectives/stealTargetGroups.yml
> +  sprite:
а описание? сделай просто наследования от описания BaseStealObjective

2024-11-24 20:10 UTC, krevetkqqq commented on Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
> +    - id: PortableCameraMonitor
добавь DS14

2024-11-24 20:11 UTC, krevetkqqq commented
не могу поставить лейбл Requested Changes. считай, что стоит

2024-11-24 20:15 UTC, krevetkqqq requested changes

2024-11-24 20:15 UTC, krevetkqqq commented on Resources/Prototypes/DeadSpace/Entities/Objects/Devices/Securities_Gadgets/portable_camera_monitor.yml
> +  name: portable camera monitor
локализация

2024-11-24 20:25 UTC, qrtDaniil requested changes
https://github.com/dead-space-server/space-station-14-resources/pull/58#issuecomment-2496208469

2024-11-24 21:02 UTC, krevetkqqq approved these changes
ну так вроде норм, посмотрим что скажет @qrtDaniil

2024-11-24 21:02 UTC, krevetkqqq commented on Resources/Prototypes/DeadSpace/Objectives/stealTargetGroups.yml
> +  parent: BaseStealObjective
это такой конец... в общем убери это, оставь как было

2024-11-24 21:10 UTC, krevetkqqq commented on Resources/Prototypes/DeadSpace/Objectives/stealTargetGroups.yml
> +  parent: BaseStealObjective
```suggestion
```

2024-11-25 14:07 UTC, qrtDaniil requested changes

2024-11-25 15:09 UTC, merged