Респрайты оружия by semkagamez
dead-space-server/space-station-14-resources pull request #61
Opened 2024-11-25 21:44 UTC by killervegetable

## Описание PR
Респрайты оружия by @semkagamez (discord)
## Изменения для патчноута
* Массивный респрайт оружия by semkagamez
## Критические изменения
* Нет

2024-11-26 12:00 UTC, qrtDaniil requested changes
И оставь старый доминатор

2024-11-26 12:00 UTC, qrtDaniil commented on Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/blueshield_gun.rsi/meta.json
> +  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/484fcb08e8e2058b81059424fb5aa77034a3fcf1, resprited by mally0352, resprite by semkagamez(discord) for Spac
Добавь пробелы везде между ником и (discord) 

:)

2024-11-26 12:29 UTC, killervegetable commented on Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/blueshield_gun.rsi/meta.json
> +  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/484fcb08e8e2058b81059424fb5aa77034a3fcf1, resprited by mally0352, resprite by semkagamez(discord) for Spac
спрайтеры не умеют писать мету

2024-11-26 15:13 UTC, SemkaGamez commented on Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/blueshield_gun.rsi/meta.json
> +  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/484fcb08e8e2058b81059424fb5aa77034a3fcf1, resprited by mally0352, resprite by semkagamez(discord) for Spac
Спрайтерам обидно за такие слова

2024-11-27 00:50 UTC, qrtDaniil requested changes
Я имел в виду везде убрать этот пробел, не только в одном файле

2024-11-27 04:48 UTC, SemkaGamez commented
> Я имел в виду везде убрать этот пробел, не только в одном файле

Это настолько важно что ли ?

2024-11-27 12:11 UTC, killervegetable commented
БЛЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯ

2024-11-27 12:13 UTC, qrtDaniil commented
> > Я имел в виду везде убрать этот пробел, не только в одном файле
> 
> Это настолько важно что ли ?

Да

2024-11-27 12:14 UTC, qrtDaniil commented
> БЛЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯ

Кинь доминатор отдельными ПР-ом ещё пожалуйста

2024-11-27 12:52 UTC, qrtDaniil commented
> > БЛЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯ
> 
> Кинь доминатор отдельными ПР-ом ещё пожалуйста

Он его ещё респрайтит, отмена пока

2024-11-27 14:26 UTC, qrtDaniil approved these changes

2024-12-06 13:07 UTC, merged