ре респрайт карго
dead-space-server/space-station-14-resources pull request #65
Opened 2024-11-27 15:46 UTC by sosooo121

## Описание PR
ре респрайт карго

## Изменения для патчноута
* Респрайт всей униформы снабжения, добавление новой, респрайт скафандров под воксов и т.д

## Критические изменения
нет

2024-11-27 16:05 UTC, qrtDaniil requested changes

2024-11-27 16:05 UTC, qrtDaniil commented on Resources/Textures/Clothing/Uniforms/Jumpsuit/qmformal.rsi/meta.json
> +  "copyright": "made by semkagamez(discord) for Space Station 14 server Dead Space",
```suggestion
  "copyright": "Made by semkagamez (discord) for Space Station 14 server Dead Space",
```
И так везде)

2024-11-30 15:04 UTC, qrtDaniil requested changes
Если ты добавляешь новые спрайты, то ты соответственно должен переписать прототипы под то что бы они работали с новыми стейтами спрайтов. 
![image](https://github.com/user-attachments/assets/b398466f-4092-4b06-9198-fe508b94c0f7)
 В некоторых ты местах вообще добавляешь новые спрайты без прототипа, это же респрайт и новых спрайтов по идеи не должно быть, там точно ничего не напутано? Всё протестируй на локалке

2024-11-30 21:25 UTC, sosooo121 commented
ну спрайты работали на локалке

2024-12-01 01:18 UTC, qrtDaniil commented
> ну спрайты работали на локалке

Тем не менее ты всё ещё добавляешь кучу спрайтов без прототипов для них, перепроверь всё

2024-12-03 20:28 UTC, qrtDaniil requested changes

2024-12-03 20:28 UTC, qrtDaniil commented on Resources/Prototypes/Entities/Clothing/Uniforms/jumpskirts.yml
> +
Перенеси прототипы новые в Resources\Prototypes\DeadSpace\Entities\Clothing\Uniforms\cargo.yml

2024-12-03 20:28 UTC, qrtDaniil commented on Resources/Prototypes/Entities/Clothing/Uniforms/jumpsuits.yml
> +
Перенеси прототипы новые в Resources\Prototypes\DeadSpace\Entities\Clothing\Uniforms\cargo.yml

2024-12-03 20:28 UTC, qrtDaniil commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/uniforms/jumpskirts.ftl
> +    .desc = Официальная юбка-комбинезон для любителей руды и стиля.
Напиши локализацию просто в прототипе

2024-12-03 20:28 UTC, qrtDaniil commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/uniforms/jumpsuits.ftl
> +    .desc = Официальный костюм для утилизаторов.
Напиши локализацию просто в прототипе

2024-12-03 20:28 UTC, qrtDaniil commented on Resources/Textures/Clothing/Uniforms/Jumpskirt/cargoformal.rsi/meta.json
Перенеси по пути Resources/Textures/DeadSpace/Clothing/Uniforms/Jumpskirt/cargoformal.rsi

2024-12-03 20:28 UTC, qrtDaniil commented on Resources/Textures/Clothing/Uniforms/Jumpskirt/salvage.rsi/meta.json
Перенеси по пути Resources/Textures/DeadSpace/Clothing/Uniforms/Jumpskirt/salvage.rsi

2024-12-03 20:28 UTC, qrtDaniil commented on Resources/Textures/Clothing/Uniforms/Jumpskirt/salvageformal.rsi/meta.json
Перенеси по пути Resources/Textures/DeadSpace/Clothing/Uniforms/Jumpskirt/salvageformal.rsi

2024-12-03 20:28 UTC, qrtDaniil commented on Resources/Textures/Clothing/Uniforms/Jumpsuit/cargo.rsi/meta.json
Перенеси по пути Resources/Textures/DeadSpace/Clothing/Uniforms/Jumpsuit/cargo.rsi

2024-12-03 20:28 UTC, qrtDaniil commented on Resources/Textures/Clothing/Uniforms/Jumpsuit/cargoformal.rsi/meta.json
Перенеси по пути Resources/Textures/DeadSpace/Clothing/Uniforms/Jumpsuit/cargoformal.rsi

2024-12-03 20:28 UTC, qrtDaniil commented on Resources/Textures/Clothing/Uniforms/Jumpsuit/salvageformal.rsi/meta.json
Перенеси по пути Resources/Textures/DeadSpace/Clothing/Uniforms/Jumpsuit/salvageformal.rsi

2024-12-03 20:46 UTC, sosooo121 commented on Resources/Textures/Clothing/Uniforms/Jumpsuit/salvageformal.rsi/meta.json
ой бл

2024-12-03 20:48 UTC, qrtDaniil commented on Resources/Textures/Clothing/Uniforms/Jumpsuit/salvageformal.rsi/meta.json
> ой бл

Я подпапку DeadSpace везде добавил просто

2024-12-04 17:43 UTC, qrtDaniil requested changes

2024-12-04 17:43 UTC, qrtDaniil commented on Resources/Prototypes/DeadSpace/Entities/Clothing/Uniforms/cargo.yml
И последнее, добавь теперь эту одежду в стартовое снаряжение/шкафы/комоды (в зависимости от одежды)

2024-12-06 19:34 UTC, qrtDaniil requested changes

2024-12-06 19:34 UTC, qrtDaniil commented on Resources/Prototypes/Loadouts/Jobs/Cargo/salvage_specialist.yml
> +    jumpsuit: ClothingUniformJumpsuitChameleon
Что то тут не так

2024-12-06 20:39 UTC, qrtDaniil approved these changes

2024-12-06 20:39 UTC, merged