Update 04.12.24
dead-space-server/space-station-14-resources pull request #73
Opened 2024-12-04 18:30 UTC by Annsannla

## Описание PR
Помимо перечисленного в патчноуте: бутылочка эфедрина в наборе вора заменена на инъектор дезоксиэфедрина. N-ка эскадрона смерти теперь не красная, как желал Хахич. У ОБР теперь сдвоенный баллон вместо большого.

## Изменения для патчноута
* Вооружение отрядов КСО было пересмотрено. Теперь все отряды ОБР и базовый РХБЗЗ вместо оружия получают предметы лодаута, позволяющие выбрать желаемое оружие (кейс и коробочка) https://discord.com/channels/1030160796401016883/1309869237657145384/1309869237657145384. 
* Отряд "Гамма" был оснащён мини-джетпаками.
* Медики "Красного" и "Гаммы" теперь получают компактные дефибрилляторы вместо обычных https://discord.com/channels/1030160796401016883/1308518628777529404/1308518628777529404. 
* Офицеры безопасности "Красного" и "Гаммы" теперь получают РПС СБ вместо пояса.

Жду ваших отзывов об отношениях нового РХБЗЗ с зомби. И энергодробовик у гаммы попробуйте, если слишком слабый - будем исправлять ||:point_right: :point_left:|| 

## Критические изменения
Нет.

2024-12-04 18:36 UTC, qrtDaniil requested changes
Перенеси все спрайты кейсов в одну папку rsi

2024-12-04 18:36 UTC, qrtDaniil commented
И название PR-а подходящее напиши

2024-12-05 11:12 UTC, Annsannla commented
@qrtDaniil Думаю всё.

2024-12-05 11:52 UTC, qrtDaniil requested changes

2024-12-05 11:52 UTC, qrtDaniil commented on Resources/Textures/Interface/Misc/job_icons.rsi/DeathSquad.png
![image](https://github.com/user-attachments/assets/f2f38cc3-9013-4499-93e6-98d69d79be72)

2024-12-05 11:52 UTC, qrtDaniil commented on Resources/Textures/DeadSpace/Other/ertloadouts/ertcases.rsi/meta.json
> +  "copyright": "Created by СyberBoich (Discord) for SS14 server Dead Space 14, resprited into ERT versions by Annsanla",
```suggestion
  "copyright": "Created by cyberboich (discord) for Space Station 14 server Dead Space, resprited into ERT versions by Annsanla",
```

2024-12-05 11:52 UTC, qrtDaniil commented on Resources/Textures/DeadSpace/Other/ertloadouts/ertboxes.rsi/meta.json
> +  "copyright": "Taken from https://github.com/ParadiseSS13/Paradise/blob/master/icons/obj/boxes.dmi and resprited by Annsanla (Discord) for Deadspace14",
```suggestion
  "copyright": "Taken from https://github.com/ParadiseSS13/Paradise/blob/master/icons/obj/boxes.dmi and resprited by annsanla (discord) for Space Station 14 server Dead Space",
```

2024-12-05 11:52 UTC, qrtDaniil commented on Resources/Locale/ru-RU/deadspace/prototypes/entities/ertloadouts.ftl
> +
```suggestion
```

2024-12-05 11:52 UTC, qrtDaniil commented on Resources/Prototypes/Catalog/thief_toolbox_sets.yml
> +  - DesoxyephedrineMedipen
thief-backpack-category-chemistry-description обнови в связи с этим изменением

2024-12-05 11:52 UTC, qrtDaniil commented on Resources/Textures/DeadSpace/Other/ertloadouts/ertboxes.rsi/meta.json
> +	    "name": "amber"
```suggestion
    "name": "amber" 
```

2024-12-06 13:13 UTC, merged