Миска для питомцев
dead-space-server/space-station-14-resources pull request #75
Opened 2024-12-05 21:29 UTC by ZweiLSS14

## Описание PR

## Изменения для патчноута

## Критические изменения

2024-12-05 22:35 UTC, qrtDaniil requested changes

2024-12-05 22:35 UTC, qrtDaniil commented on Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_cups.yml
> +        maxVol: 40
Перенеси в файл по пути Resources/Prototypes/DeadSpace/Entities/Objects/Consumable/Drinks/pet_bowl.yml

2024-12-05 22:35 UTC, qrtDaniil commented on Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
> +    - id: PetBowlWater
В самый конец списка помести

2024-12-05 22:35 UTC, qrtDaniil commented on Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
> +    - id: PetBowlWater
И приписку `# DS14` добавь

2024-12-05 22:35 UTC, qrtDaniil commented on Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
> +    - id: PetBowlWater
В самый конец списка помести

2024-12-05 22:35 UTC, qrtDaniil commented on Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
> +    - id: PetBowlWater
И приписку `# DS14` добавь

2024-12-05 22:57 UTC, qrtDaniil requested changes

2024-12-05 22:57 UTC, qrtDaniil commented on Resources/Prototypes/DeadSpace/Entities/Objects/Consumable/Drinks/pet_bowl.yml
> +  name: Pets water bowl
Локализацию прям тут напиши

2024-12-05 22:59 UTC, ZweiLSS14 commented on Resources/Prototypes/DeadSpace/Entities/Objects/Consumable/Drinks/pet_bowl.yml
> +  name: Pets water bowl
То есть на русском написать просто?

2024-12-06 01:30 UTC, qrtDaniil approved these changes

2024-12-06 13:10 UTC, merged