бафф медиков обр
dead-space-server/space-station-14-resources pull request #83
Opened 2024-12-08 11:51 UTC by Annsannla

## Описание PR
Пояс ОБР СБ у Эмбер заменён на пояс СБ, так как мне секурити голопроектор кажется более полезным предметом, чем дополнительные наручники (можно оградить зону во время прибытия представителя ЦК, чтобы было удобнее?).

Добавлен пояс медика ОБР для Красного и Гаммы. Я считаю эти отряды достаточно продвинутыми, чтобы использовать что-то серьёзнее наборов от ушибов и бинтов. К тому же вероятно планирую в будущем давать персональную аптечку первой помощи каждому ОБР, и на фоне этого у медика должно быть медикаментов поболее, чем дополнительная пара бутылочек омнизина. Выше качество каждой боевой единицы, за счёт сокращения количества сотрудников.

Переносные зарядники делают энергетическое оружие ультимативным вариантом во время революции. Лучший урон, хитскан, ещё и потенциально бесконечный боезапас. От одного элемента явно стоит отказаться. 

Рентгеновская пушка и продвинутый лазган как по мне способны составить конкуренцию в своих категориях, так что решил добавить.

## Изменения для патчноута
* Переносные зарядники вырезаны из лодаутов.
* Продвинутый лазерный пистолет добавлен в лодаут отряду Гамма, как второстепенный.
* Рентгеновская пушка добавлена в лодаут отряду Красный, как основное.
* Медики ОБР отрядов Красный и Гамма получили пояса с продвинутой медициной.

## Критические изменения
Нет.

2024-12-11 16:28 UTC, qrtDaniil commented
![image](https://github.com/user-attachments/assets/a196a9e4-263f-41af-8754-c6eea3cc2755)
Отказано

2024-12-11 16:33 UTC, qrtDaniil requested changes

2024-12-11 16:33 UTC, qrtDaniil commented on Resources/Prototypes/DeadSpace/Roles/Jobs/CentComm/emergencyresponseteam.yml
> +    belt: ClothingBeltSecurityFilled
Так а зачем, отредачь ClothingBeltERTSecurityFilled просто

2024-12-11 16:33 UTC, qrtDaniil commented on Resources/Locale/ru-RU/ss14-ru/prototypes/catalog/fills/items/belt.ftl
> +ent-ClothingBeltMedicalFilledERT = { ent-ClothingBeltMedical }
```suggestion
ent-ClothingBeltERTMedicalFilled = { ent-ClothingBeltMedical }
```
И так везде

2024-12-11 23:10 UTC, Annsannla commented on Resources/Prototypes/DeadSpace/Roles/Jobs/CentComm/emergencyresponseteam.yml
> +    belt: ClothingBeltSecurityFilled
Ээ, ладно.

2024-12-12 08:21 UTC, Annsannla commented
У меня складывалось ощущение, что расположение ERT в ID неправильное, но раз ты так хочешь.

2024-12-13 20:13 UTC, merged