Массовый респрайт карго
dead-space-server/space-station-14-resources pull request #9
Opened 2024-10-12 15:52 UTC by ilyasassiks

## Описание PR

Массовый респрайт карго по просьбе КМа
## Изменения для патчноута

* Масс респрайт карго
* Добавление шкафа и скафандра ведущего утиля

## Критические изменения

Нету

2024-10-12 15:56 UTC, qrtDaniil requested changes
Кто такой `LeadSalvage`, я знаю только `SeniorSalvageSpecialist`

2024-10-12 15:56 UTC, qrtDaniil commented on Resources/Locale/en-US/prototypes/access/accesses.ftl
> +id-card-access-level-lead-salvage = Lead Salvage
Не нужно

2024-10-12 16:09 UTC, qrtDaniil requested changes
Проверь спрайты на локалке, а то мне кажется там много где может быть беда с метой

2024-10-12 16:09 UTC, qrtDaniil commented on Resources/Prototypes/Entities/Structures/Storage/Closets/Lockers/lockers.yml
> +    access: [["SeniorSalvage"]]
Так доступ `SeniorSalvage` или `SeniorSalvageSpecialist`?

2024-10-12 16:09 UTC, qrtDaniil commented on Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
> +  - SeniorSalvageSpecialist
А тут SeniorSalvageSpecialist

2024-10-12 16:09 UTC, qrtDaniil commented on Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
> +  - SeniorSalvageSpecialist
И тут

2024-10-12 16:09 UTC, qrtDaniil commented on Resources/Textures/Clothing/Head/Hardsuits/salvage.rsi/meta.json
> -      "name": "icon-flash"
А icon-flash за что пустил под нож?

2024-10-12 16:10 UTC, ilyasassiks commented on Resources/Textures/Clothing/Head/Hardsuits/salvage.rsi/meta.json
> -      "name": "icon-flash"
пм сделал такую мету

2024-10-12 16:11 UTC, qrtDaniil commented on Resources/Textures/Clothing/Head/Hardsuits/salvage.rsi/meta.json
> -      "name": "icon-flash"
> пм сделал такую мету

А тебе нужно затестить получается и пофиксить

2024-10-12 18:29 UTC, ilyasassiks commented
я все затестил

2024-10-12 19:22 UTC, qrtDaniil requested changes

2024-10-12 19:22 UTC, qrtDaniil commented on Resources/Prototypes/Access/misc.yml
> +  - LeadSalvage
```suggestion
  - SeniorSalvage
```

2024-10-12 19:22 UTC, qrtDaniil commented on Resources/Prototypes/Catalog/Fills/Lockers/cargo.yml
> +  id: LockerSeniorSalvageSpecialistFilledHardsuit
Локализацию забыл

2024-10-12 19:22 UTC, qrtDaniil commented on Resources/Prototypes/Entities/Clothing/Head/hardsuit-helmets.yml
> -        shader: unshaded
Ну если это всего лишь респрайт зачем прототип переписывать

2024-10-12 19:22 UTC, qrtDaniil commented on Resources/Prototypes/Entities/Clothing/Head/hardsuit-helmets.yml
> +  name: senior salvage hardsuit helmet
Строчку name можно удалить, + нет локализации

2024-10-12 19:22 UTC, qrtDaniil commented on Resources/Textures/Clothing/Uniforms/Jumpsuit/cargotech.rsi/equipped-INNERCLOTHING-monkey.png
А манки что вам сделал 😢

2024-10-12 19:34 UTC, ilyasassiks commented on Resources/Prototypes/Entities/Clothing/Head/hardsuit-helmets.yml
> -        shader: unshaded
потому что нету спрайтов, под существующие подстраивался

2024-10-12 20:04 UTC, qrtDaniil requested changes

2024-10-12 20:04 UTC, qrtDaniil commented on Resources/Textures/Clothing/Head/Hardsuits/salvage.rsi/meta.json
> +  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/4f6190e2895e09116663ef282d3ce1d8b35c032e. Resprite by Ravanesus for DeadSpace14",
```suggestion
  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/4f6190e2895e09116663ef282d3ce1d8b35c032e. Resprite by ravanesus (discord) for Space Station 14 server Dead Space",
```

2024-10-12 20:04 UTC, qrtDaniil commented on Resources/Textures/Clothing/Head/Hardsuits/seniorsalvage.rsi/meta.json
> +  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/4f6190e2895e09116663ef282d3ce1d8b35c032e.Resprite. by Ravanesus for DeadSpace14",
```suggestion
  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/4f6190e2895e09116663ef282d3ce1d8b35c032e. Resprite by ravanesus (discord) for Space Station 14 server Dead Space",
```

2024-10-12 20:04 UTC, qrtDaniil commented on Resources/Textures/Clothing/Head/Hardsuits/spatiohelm.rsi/meta.json
> +  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/4f6190e2895e09116663ef282d3ce1d8b35c032e.Resprite. by Ravanesus for DeadSpace14",
```suggestion
  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/4f6190e2895e09116663ef282d3ce1d8b35c032e. Resprite by ravanesus (discord) for Space Station 14 server Dead Space",
```

2024-10-12 20:04 UTC, qrtDaniil commented on Resources/Textures/Clothing/Head/Hats/beret_qm.rsi/meta.json
> +  "copyright": "made by timekor (Discord) for Space Station 14 server Dead Space",
```suggestion
  "copyright": "Made by timekor (discord) for Space Station 14 server Dead Space",
```

2024-10-12 20:04 UTC, qrtDaniil commented on Resources/Textures/Clothing/Head/Soft/cargosoft.rsi/meta.json
> +  "copyright": "made by timekor (Discord) for Space Station 14 server Dead Space",
```suggestion
  "copyright": "Made by timekor (discord) for Space Station 14 server Dead Space",
```

2024-10-12 20:04 UTC, qrtDaniil commented on Resources/Textures/Clothing/Neck/Cloaks/qm.rsi/meta.json
> +  "copyright": "made by timekor (Discord) for Space Station 14 server Dead Space",
```suggestion
  "copyright": "Made by timekor (discord) for Space Station 14 server Dead Space",
```

2024-10-12 20:04 UTC, qrtDaniil commented on Resources/Textures/Clothing/Neck/mantles/qmmantle.rsi/meta.json
> +  "copyright": "made by timekor (Discord) for Space Station 14 server Dead Space",
```suggestion
  "copyright": "Made by timekor (discord) for Space Station 14 server Dead Space",
```

2024-10-12 20:04 UTC, qrtDaniil commented on Resources/Textures/Clothing/OuterClothing/Hardsuits/salvage.rsi/meta.json
> +  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/4f6190e2895e09116663ef282d3ce1d8b35c032e. Resprite by Ravanesus for DeadSpace14",
```suggestion
  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/4f6190e2895e09116663ef282d3ce1d8b35c032e. Resprite by ravanesus (discord) for Space Station 14 server Dead Space",
```

2024-10-12 20:04 UTC, qrtDaniil commented on Resources/Textures/Clothing/OuterClothing/Hardsuits/seniorsalvage.rsi/meta.json
> +  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/4f6190e2895e09116663ef282d3ce1d8b35c032e. Resprite by Ravanesus for DeadSpace14",
```suggestion
  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/4f6190e2895e09116663ef282d3ce1d8b35c032e. Resprite by ravanesus (discord) for Space Station 14 server Dead Space",
```

2024-10-12 20:04 UTC, qrtDaniil commented on Resources/Textures/Clothing/OuterClothing/Hardsuits/spatio.rsi/meta.json
> +  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/4f6190e2895e09116663ef282d3ce1d8b35c032e. Resprite by Ravanesus for DeadSpace14",
```suggestion
  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/4f6190e2895e09116663ef282d3ce1d8b35c032e. Resprite by ravanesus (discord) for Space Station 14 server Dead Space",
```

2024-10-12 20:04 UTC, qrtDaniil commented on Resources/Textures/Clothing/Uniforms/Jumpskirt/cargotech.rsi/meta.json
> +  "copyright": "made by timekor (Discord) for Space Station 14 server Dead Space",
```suggestion
  "copyright": "Made by timekor (discord) for Space Station 14 server Dead Space",
```

2024-10-12 20:04 UTC, qrtDaniil commented on Resources/Textures/Clothing/Uniforms/Jumpskirt/qmformalskirt.rsi/meta.json
> +  "copyright": "made by timekor (Discord) for Space Station 14 server Dead Space",
```suggestion
  "copyright": "Made by timekor (discord) for Space Station 14 server Dead Space",
```

2024-10-12 20:04 UTC, qrtDaniil commented on Resources/Textures/Clothing/Uniforms/Jumpskirt/qmturtleskirt.rsi/meta.json
> +  "copyright": "made by timekor (Discord) for Space Station 14 server Dead Space",
```suggestion
  "copyright": "Made by timekor (discord) for Space Station 14 server Dead Space",
```

2024-10-12 20:04 UTC, qrtDaniil commented on Resources/Textures/Clothing/Uniforms/Jumpsuit/cargotech.rsi/meta.json
> +  "copyright": "made by timekor (Discord) for Space Station 14 server Dead Space",
```suggestion
  "copyright": "Made by timekor (discord) for Space Station 14 server Dead Space",
```

2024-10-12 20:04 UTC, qrtDaniil commented on Resources/Textures/Clothing/Uniforms/Jumpsuit/salvage.rsi/meta.json
> +  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/0a1ae39f0fb7353b0704f27d1599a567891f727c, Resprite by Ravanesus for DeadSpace 14",
```suggestion
  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/0a1ae39f0fb7353b0704f27d1599a567891f727c. Resprite by ravanesus (discord) for Space Station 14 server Dead Space",
```

2024-10-12 20:04 UTC, qrtDaniil commented on Resources/Textures/Clothing/Uniforms/Jumpsuit/qmturtle.rsi/meta.json
> +  "copyright": "made by timekor (Discord) for Space Station 14 server Dead Space",
```suggestion
  "copyright": "Made by timekor (discord) for Space Station 14 server Dead Space",
```

2024-10-12 20:04 UTC, qrtDaniil commented on Resources/Textures/Clothing/Uniforms/Jumpsuit/qmformal.rsi/meta.json
> +  "copyright": "made by timekor (Discord) for Space Station 14 server Dead Space",
```suggestion
  "copyright": "Made by timekor (discord) for Space Station 14 server Dead Space",
```

2024-10-12 22:55 UTC, qrtDaniil requested changes

2024-10-12 22:55 UTC, qrtDaniil commented on Resources/Prototypes/Catalog/Fills/Lockers/cargo.yml
> +  id: SuitStorageSeniorSalvageSpecialistFilled
SuitStorage хранятся в `Resources\Prototypes\Catalog\Fills\Lockers\suit_storage.yml`

2024-10-13 11:52 UTC, qrtDaniil requested changes

2024-10-13 11:52 UTC, qrtDaniil commented on Resources/Prototypes/Catalog/Fills/Lockers/suit_storage.yml
> +      - id: ClothingMaskGasExplorer
```suggestion
      - id: OxygenTankFilled
      - id: ClothingShoesBootsMag
      - id: ClothingOuterHardsuitSeniorSalvage
      - id: ClothingMaskGasExplorer
```

2024-10-13 11:54 UTC, qrtDaniil approved these changes

2024-10-21 16:26 UTC, merged