Mime and Deer
dead-space-server/space-station-14-resources pull request #95
Opened 2024-12-14 08:13 UTC by YarikVodila22817

## Описание PR

Добавлены шарф мима и рога оленя.

## Изменения для патчноута

* Добавлен шарф мима.
* Добавлены рога оленя.

## Критические изменения

Нет.

2024-12-14 15:30 UTC, qrtDaniil requested changes
Уээээ???
![image](https://github.com/user-attachments/assets/c333d909-af0e-4215-b12a-0c8250900eaf)
![image](https://github.com/user-attachments/assets/30c277a5-dcc9-449c-882e-585b0747f083)

2024-12-14 15:59 UTC, YarikVodila22817 commented
> Уээээ??? ![image](https://private-user-images.githubusercontent.com/58003418/395792212-c333d909-af0e-4215-b12a-0c8250900eaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxOTIyMjQsIm5iZiI6MTczNDE5MTkyNCwicGF0aCI6Ii81ODAwMzQxOC8zOTU3OTIyMTItYzMzM2Q5MDktYWYwZS00MjE1LWIxMmEtMGM4MjUwOTAwZWFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDE1NTg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1MTM4YmEwMWNkYWI1MzY4MzY1NGI2ZmFkNmQ2MTNmZjY4YWM4Y2FmMWQzNTQ0MzJlN2ZkOWE4NWVlZWQ0NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NzWbUH-vcvEsGn9n9i9H6ljTit9ps6cLLqhjNnC-DBU) ![image](https://private-user-images.githubusercontent.com/58003418/395792217-30c277a5-dcc9-449c-882e-585b0747f083.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxOTIyMjQsIm5iZiI6MTczNDE5MTkyNCwicGF0aCI6Ii81ODAwMzQxOC8zOTU3OTIyMTctMzBjMjc3YTUtZGNjOS00NDljLTg4MmUtNTg1YjA3NDdmMDgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDE1NTg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhOTkxNjc4MTMzYTJkNDUwYmVlN2Q5MGY2YTQ4MGRmZDRlOTQxMTg1MjQ2OWVlYzI5MTAwZjQ1NzE2ZGY0OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iP2QxNj8NNgB-xZSmQXkVxNyNOC-dbxnqvlz2TVkta0)

реально уэээээ

2024-12-14 16:43 UTC, qrtDaniil commented
> > Уээээ??? ![image](https://private-user-images.githubusercontent.com/58003418/395792212-c333d909-af0e-4215-b12a-0c8250900eaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxOTIyMjQsIm5iZiI6MTczNDE5MTkyNCwicGF0aCI6Ii81ODAwMzQxOC8zOTU3OTIyMTItYzMzM2Q5MDktYWYwZS00MjE1LWIxMmEtMGM4MjUwOTAwZWFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDE1NTg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1MTM4YmEwMWNkYWI1MzY4MzY1NGI2ZmFkNmQ2MTNmZjY4YWM4Y2FmMWQzNTQ0MzJlN2ZkOWE4NWVlZWQ0NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NzWbUH-vcvEsGn9n9i9H6ljTit9ps6cLLqhjNnC-DBU) ![image](https://private-user-images.githubusercontent.com/58003418/395792217-30c277a5-dcc9-449c-882e-585b0747f083.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxOTIyMjQsIm5iZiI6MTczNDE5MTkyNCwicGF0aCI6Ii81ODAwMzQxOC8zOTU3OTIyMTctMzBjMjc3YTUtZGNjOS00NDljLTg4MmUtNTg1YjA3NDdmMDgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDE1NTg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhOTkxNjc4MTMzYTJkNDUwYmVlN2Q5MGY2YTQ4MGRmZDRlOTQxMTg1MjQ2OWVlYzI5MTAwZjQ1NzE2ZGY0OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iP2QxNj8NNgB-xZSmQXkVxNyNOC-dbxnqvlz2TVkta0)
> 
> реально уэээээ

У тебя так же?

2024-12-19 12:59 UTC, qrtDaniil approved these changes

2024-12-20 23:33 UTC, merged