клан паука
dead-space-server/space-station-14-resources pull request #97
Opened 2024-12-14 12:15 UTC by killervegetable

## Описание PR
(наконец) добавил кейс для гитары и баннер клана паука по просьбе 0black_cat0 (discord)
## Изменения для патчноута
* Добавлен гитарный кейс, для самых тихих музыкантов, спрайт by GribGear (Discord)
## Критические изменения
* нет

2024-12-14 15:28 UTC, qrtDaniil requested changes

2024-12-14 15:28 UTC, qrtDaniil commented on Resources/Prototypes/tags.yml
> +  id: SniperWeapon
В Resources/Prototypes/DeadSpace/tags.yml

2024-12-14 15:28 UTC, qrtDaniil commented on Resources/Prototypes/Entities/Clothing/Back/case.yml
> +  name: Гитарный кейс
```suggestion
  name: гитарный кейс
```

2024-12-14 15:28 UTC, qrtDaniil commented on Resources/Prototypes/DeadSpace/Entities/Structures/Decoration/banners.yml
> +  name: Знамя клана паука
```suggestion
  name: знамя клана паука
```

2024-12-14 15:28 UTC, qrtDaniil commented on Resources/Prototypes/Entities/Clothing/Back/case.yml
> +  parent: [ClothingBeltBase, ClothingSlotBase ]
```suggestion
  parent: [ ClothingBeltBase, ClothingSlotBase ]
```

2024-12-14 15:28 UTC, qrtDaniil commented on Resources/Prototypes/Entities/Clothing/Back/case.yml
> +  id: ClothingBackpackCase
```suggestion
  id: ClothingBackpackGuitarCase
```

2024-12-15 03:42 UTC, killervegetable commented on Resources/Prototypes/tags.yml
> +  id: SniperWeapon
ou no

2024-12-19 12:39 UTC, qrtDaniil approved these changes
Потом поменяет спрайт флага

2024-12-20 23:33 UTC, merged